#!/bin/bash

function xprofile () {
    PROFILE=${1:-"Default"};
    printf "\e]50;SetProfile=%s\a" "$PROFILE";
}

function clean () {
    rm -fv *~ .*~
}

function rclean () {
    find . -name '*~' -o -name '.*~' | xargs rm -fv
}

function xtitle () {
    printf "\e]0;%s\007" "$1";
}

function xsize () {
    WIDTH=${1:-"80"};
    HEIGHT=${2:-"50"};
    printf "\e[8;%d;%dt" $HEIGHT $WIDTH;
}

function clear () {
    printf "\e[2J"
}

function ts () {
    export TS=$(date '+%Y-%m-%d %H:%M:%S')
}

# my usual crontab comment
cron_header () {
    echo "# min hr day mon     dow       command"
    echo "# --- -- --- --- -----------  --------------------------------------------------"
}

# an alternate crontab comment I've played with
cron_footer () {
echo "
# ^ ^ ^ ^ ^           ^- command to execute
# │ │ │ │ └─ day of week (0 - 6) (0 to 6 are Sunday to Saturday)
# │ │ │ └─── month (1 - 12)
# │ │ └───── day of month (1 - 31)
# │ └─────── hour (0 - 23)
# └───────── min (0 - 59)"
}

function cycle_term_bgcolor () {
  local DEFAULT_LIST="000000:770000:000044:004400:005566:660066:660055:555500"
  local DEFAULT_COLOR="000000"
  export TERM_BGCOLOR_LIST=${TERM_BGCOLOR_LIST:-$DEFAULT_LIST}
  export TERM_BGCOLOR=${TERM_BGCOLOR:-$DEFAULT_COLOR}
  IFS=':' read -r -a array <<< "$TERM_BGCOLOR_LIST"
  for index in "${!array[@]}"; do
    if [[ "${array[index]}" == "$TERM_BGCOLOR" ]]; then
      i=$(( (index + 1) % ${#array[@]} ))
      export TERM_BGCOLOR="${array[i]}"
      set_term_color_palette --background $TERM_BGCOLOR
      return
    fi
  done
  # we didn't find the current color on the list
  export TERM_BGCOLOR="${array[0]}"
  set_term_color_palette --background $TERM_BGCOLOR
}

function set_term_titlecolor () {
  perl -e '
my $color = shift @ARGV;
my($r,$g,$b) = $color =~ /^([0-f]{2})([0-f]{2})([0-f]{2})$/;
unless (defined $r && defined $g && defined $b) {
  if ( ($r,$g,$b) = $color =~ /^([0-f]{1})([0-f]{1})([0-f]{1})$/ ) {
    ($r,$g,$b) = ( $r x 2, $g x 2, $b x 2 );
  }
}
if ( defined $r && defined $g && defined $b ) {
  ($r,$g,$b) = ( hex($r), hex($g), hex($b) );
  print "\033]6;1;bg;red;brightness;$r\a"
      . "\033]6;1;bg;green;brightness;$g\a"
      . "\033]6;1;bg;blue;brightness;$b\a"
}
elsif ( $color =~ /^d?e?f?a?u?l?t?/i ) {
  print "\033]6;1;bg;*;default\a";
}
else {
  print STDERR "Unknown color specification: '$color'\n";
  exit 1;
}
' "$@"
}
