#!/bin/bash
#
alias emacs="/Applications/Emacs.app/Contents/MacOS/Emacs -nw"

if is_local; then
    export EDITOR=xemacs
    alias xe=xemacs
else
    export EDITOR=emacs
    export GIT_EDITOR=emacs
    alias xe=emacs
fi

export GREP_COLOR='30;43'
export GREP_OPTIONS='--color=auto'
#alias grep='grep --color=auto'

alias clean='rm -fv *~ .*~'

alias clear='printf "\e[2J"'

alias rsync_pwd_to='rsync -avz .'
