#!/usr/bin/env bash

function is_interactive() {
    [[ $- == *i* ]]
}

function scroll_if_at_bottom () {
    is_interactive && printf "\n\e[1A" # newline, cursor up 1 line
}
scroll_if_at_bottom

function save_cursor () {
    is_interactive && printf "\e[s" # \e[s saves cursor position
}

function restore_cursor_clear_down () {
    is_interactive && printf "\e[u\e[J" # restore cursor, clear screen from cursor down
}

function source_file () {
    FILE=$1
    PRINTERR=$2
    if [[ -f $FILE ]]; then
        save_cursor
        is_interactive && printf "Sourcing %s ...\n" $FILE
        source $FILE
        restore_cursor_clear_down
    elif [[ "$PRINTERR" != "" ]]; then
        is_interactive && echo ERROR: Unable to find $FILE >> /dev/stderr
    fi
}

# preferred minimal prompt: "user@host: path" in title, $ or # on command line
export PS1="\[\e]0;\u@\h: \w\007\]\\$ "

if [[ -e /usr/share/zoneinfo/America/New_York ]]; then
    export TZ=/usr/share/zoneinfo/America/New_York
fi
